# Generated by Django 2.0.5 on 2018-05-22 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view users'), ('edit_user', 'Can edit users'), ('view_group', 'Can view groups'), ('edit_group', 'Can edit groups'), ('view_staff', 'Can view staff'), ('edit_staff', 'Can edit staff'), ('impersonate_user', 'Can impersonate users'))},
        ),
    ]
