# Generated by Django 2.0.5 on 2018-05-22 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180522_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone number of user')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='website')),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'fimale'), ('', 'unspecified')], default='', max_length=2, verbose_name='gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
