# Generated by Django 2.0.5 on 2018-06-07 04:02

import django.contrib.sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='domain',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.contrib.sites.models._simple_domain_name_validator], verbose_name='domain name'),
            preserve_default=False,
        ),
    ]
