# Generated by Django 2.0.6 on 2018-06-22 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='product.Product'),
        ),
    ]
